### ISSUE TITLE
Undo autocorrection does not seem to work on Flutter apps. 

### ISSUE THREAD

**Issue by xevifar** [FleksySDK/VirtualKeyboardSDK#65]
It seems that the undo autocorrection does not work on some flutter apps. 
In the past, this was a problem on the flutter input connection itself, but we have not tested it again. 

A possible app to test this is this one:
https://play.google.com/store/apps/details?id=io.flutter.demo.gallery

Undoing autocorrect word via the backspace button does not work.

**Comment by xevifar** [comment]
This has been addressed and now it works correctly. 
Tested on the Gallery app:

https://github.com/FleksySDK/VirtualKeyboardSDK/assets/61009196/6d7d7ade-5efb-4f2a-bbb8-6da2d5ebb397

**Comment by systemofapwne** [comment]
I still encounter this issue a lot on Android.

E.g. in **brave browser** (not sure, if flutter), if I keep on typing words into the adresse/search bar, the very first word cannot be corrected - I always need to type some random word, press space, delete write a second word and from now on, auto correction works. This bug happens like every other time and is not triggered reliably.

But in another app, fluffy chat (a Matrix client), autocorrection is completely broken. Whatever I type, it always corrects for a word it thinks that I typed. I cannot cycle through any other words with up/down gesture. I cannot even add new words in here.
This app is indeed a flutter app.

I really hope, this gets fixed. Fleksy became a bit annoying to use in brave and is borderline usable up to unsuable in fluffy chat.
